#
#                                          - mayank19o7
#  o     o          o
#  8b   d8          8
#  8`b d'8 .oPYo.  o8P o    o .oPYo. .oPYo. odYo.
#  8 `o' 8 .oooo8   8  8    8 8    8 8oooo8 8' `8
#  8     8 8    8   8  8    8 8    8 8.     8   8
#  8     8 `YooP8   8  `YooP' `YooP8 `Yooo' 8   8
# :..::::..:.....:::..::.....::....8 :.....:..::..:::::
# ::::::::::::::::::::::::::::::ooP'.::::::::::::::::::
# ::::::::::::::::::::::::::::::...::::::::::::::::::::
# -----------------------------------------------------

[config]
version_check = false

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/styles/matugen.css'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = "if pgrep -x cava >/dev/null; then pkill -USR2 cava; fi"
