#
#                                          - mayank19o7
#  o     o          o
#  8b   d8          8
#  8`b d'8 .oPYo.  o8P o    o .oPYo. .oPYo. odYo.
#  8 `o' 8 .oooo8   8  8    8 8    8 8oooo8 8' `8
#  8     8 8    8   8  8    8 8    8 8.     8   8
#  8     8 `YooP8   8  `YooP' `YooP8 `Yooo' 8   8
# :..::::..:.....:::..::.....::....8 :.....:..::..:::::
# ::::::::::::::::::::::::::::::ooP'.::::::::::::::::::
# ::::::::::::::::::::::::::::::...::::::::::::::::::::
# -----------------------------------------------------

[config]
version_check = false

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/styles/matugen.css'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = "if pgrep -x btop >/dev/null; then pkill -USR2 btop; fi"

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = "if pgrep -x cava >/dev/null; then pkill -USR2 cava; fi"

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc'
output_path = '~/.config/dunst/dunstrc'
post_hook = "pkill dunst && dunst &"

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/themes/matugen.ini'

[templates.lazygit]
input_path = '~/.config/matugen/templates/lazygit-config.yml'
output_path = '~/.config/lazygit/config.yml'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/matugen.conf'
post_hook = 'if pgrep -x hyprland;then hyprctl reload;fi'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all matugen"

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-flavor.toml'
output_path = '~/.config/yazi/flavors/matugen.yazi/flavor.toml'
