#
#                                           - mayank19o7
#
#   8                              o   o
#   8                                  8
#   8 .oPYo. .oooo. o    o .oPYo. o8  o8P
#   8 .oooo8   .dP  8    8 8    8  8   8
#   8 8    8  oP'   8    8 8    8  8   8
#   8 `YooP8 `Yooo' `YooP8 `YooP8  8   8
# ::..:.....::.....::....8 :....8 :..::..::::::::::::::
# ::::::::::::::::::::ooP'.::ooP'.:::::::::::::::::::::
# ::::::::::::::::::::...::::...:::::::::::::::::::::::
# -----------------------------------------------------

git:
  pagers:
    - pager: delta --dark --paging=never
    - colorArg: always
gui:
  nerdFontsVersion: "3"
  authorColors:
    '*': '{{colors.source_color.default.hex}}'
  theme:
    activeBorderColor:
      - '{{colors.primary.default.hex}}'
      - bold
    inactiveBorderColor:
      - '{{colors.outline_variant.default.hex}}'
    searchingActiveBorderColor:
      - '{{colors.tertiary.default.hex}}'
    optionsTextColor:
      - '{{colors.secondary.default.hex}}'
    selectedLineBgColor:
      - '{{colors.surface_container_low.default.hex}}'
    cherryPickedCommitFgColor:
      - '{{colors.primary.default.hex}}'
    cherryPickedCommitBgColor:
      - 'bg'
    unstagedChangesColor:
      - '{{colors.error.default.hex}}'
    defaultFgColor:
      - '{{colors.on_surface_variant.default.hex}}'
