[mgr]
cwd = { fg = "{{colors.tertiary.default.hex}}", bold = true }

# Hovered
hovered = { bg = "{{colors.surface_container_low.default.hex}}" }
preview_hovered = { underline = false }

# Find
find_keyword = { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.secondary_container.default.hex}}" }
find_position = { fg = "{{colors.tertiary.default.hex}}", bold = true, italic = true }

# Marker
marker_copied   = { fg = "{{colors.secondary.default.hex}}", bg = "{{colors.secondary.default.hex}}" }
marker_cut      = { fg = "{{colors.error.default.hex}}", bg = "{{colors.error.default.hex}}" }
marker_marked   = { fg = "{{colors.tertiary_container.default.hex}}", bg = "{{colors.tertiary_container.default.hex}}" }
marker_selected = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.primary.default.hex}}" }

# Count
count_copied   = { fg = "{{colors.surface.default.hex}}", bg = "{{colors.secondary.default.hex}}", bold = true }
count_cut      = { fg = "{{colors.surface.default.hex}}", bg = "{{colors.error.default.hex}}", bold = true }
count_selected = { fg = "{{colors.surface.default.hex}}", bg = "{{colors.primary.default.hex}}", bold = true }

# Border
border_symbol = "│"
border_style  = { fg = "{{colors.outline_variant.default.hex}}" }

[tabs]
active   = { fg = "{{colors.surface_container.default.hex}}", bg = "{{colors.primary_fixed_dim.default.hex}}", bold = true }
inactive = { fg = "{{colors.primary_fixed_dim.default.hex}}", bg = "{{colors.surface_container.default.hex}}" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
# Normal mode
normal_main = { fg = "{{colors.surface_container.default.hex}}", bg = "{{colors.primary.default.hex}}", bold = true }
normal_alt  = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.surface_container.default.hex}}" }

# Select mode
select_main = { fg = "{{colors.surface_container.default.hex}}", bg = "{{colors.tertiary.default.hex}}", bold = true }
select_alt  = { fg = "{{colors.tertiary.default.hex}}", bg = "{{colors.surface_container.default.hex}}" }

# Unset mode
unset_main = { fg = "{{colors.surface_container.default.hex}}", bg = "{{colors.secondary.default.hex}}", bold = true }
unset_alt  = { fg = "{{colors.secondary.default.hex}}", bg = "{{colors.surface_container.default.hex}}" }

[status]
overall = { bg = "{{colors.surface_container_high.default.hex}}" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_type  = { fg = "{{colors.primary.default.hex}}" }
perm_read  = { fg = "{{colors.tertiary.default.hex}}" }
perm_write = { fg = "{{colors.error.default.hex}}" }
perm_exec  = { fg = "{{colors.secondary.default.hex}}" }
perm_sep   = { fg = "{{colors.outline_variant.default.hex}}" }

# Progress
progress_label  = { fg = "{{colors.on_surface.default.hex}}" }
progress_normal = { fg = "{{colors.secondary.default.hex}}", bg = "{{colors.secondary_container.default.hex}}" }
progress_error  = { bg = "{{colors.error.default.hex}}" }

[which]
cols = 3
mask = { bg = "{{colors.surface.default.hex}}" }
cand = { fg = "{{colors.primary.default.hex}}", bold = true }
rest = { fg = "{{colors.on_surface_variant.default.hex}}", italic = true }
desc = { fg = "{{colors.on_surface.default.hex}}" }
separator = " - "
separator_style = { fg = "{{colors.on_surface_variant.default.hex}}" }

[confirm]
border  = { fg = "{{colors.outline_variant.default.hex}}" }
title   = { fg = "{{colors.on_surface_variant.default.hex}}", bold = true }
content = { fg = "{{colors.on_surface_variant.default.hex}}", bold = true }
list    = { fg = "{{colors.on_surface_variant.default.hex}}" }

btn_yes = { fg = "{{colors.on_primary.default.hex}}", bg = "{{colors.primary.default.hex}}", bold = true }
btn_no  = { fg = "{{colors.on_surface_variant.default.hex}}", bg = "{{colors.surface_container.default.hex}}" }

[spot]
border   = { fg = "{{colors.outline_variant.default.hex}}" }
title    = { fg = "{{colors.on_surface_variant.default.hex}}", bold = true }
tbl_col  = { fg = "{{colors.primary.default.hex}}" }
tbl_cell = { bg = "{{colors.surface.default.hex}}" }

[notify]
# Notification title
title_info  = { fg = "{{colors.primary.default.hex}}" }
title_warn  = { fg = "{{colors.tertiary.default.hex}}" }
title_error = { fg = "{{colors.error.default.hex}}" }

[pick]
border   = { fg = "{{colors.outline_variant.default.hex}}", bold = true }
active   = { fg = "{{colors.on_surface.default.hex}}" }
inactive = { fg = "{{colors.on_surface_variant.default.hex}}" }

[input]
border   = { fg = "{{colors.outline_variant.default.hex}}" }
title    = { fg = "{{colors.on_surface_variant.default.hex}}", bold = true }
value    = { fg = "{{colors.on_surface.default.hex}}" }
selected = { bg = "{{colors.surface_container.default.hex}}" }

[completion]
border   = { fg = "{{colors.outline_variant.default.hex}}", bold = true }
active   = { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.surface_container.default.hex}}" }
inactive = { fg = "{{colors.on_surface_variant.default.hex}}" }

[tasks]
border  = { fg = "{{colors.outline_variant.default.hex}}" }
title   = { fg = "{{colors.on_surface_variant.default.hex}}", bold = true }
hovered = { bg = "{{colors.surface_container.default.hex}}" }

[help]
on      = { fg = "{{colors.primary.default.hex}}" }
run     = { fg = "{{colors.secondary.default.hex}}" }
desc    = { fg = "{{colors.on_surface_variant.default.hex}}", italic = true }
hovered = { bg = "{{colors.surface_container_low.default.hex}}" }
footer  = { fg = "{{colors.on_surface.default.hex}}", bg = "{{colors.surface.default.hex}}", bold = true }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "{{colors.tertiary.default.hex}}" },

	# Media
	{ mime = "{audio,video}/*", fg = "{{colors.tertiary.default.hex}}" },

	# archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "{{colors.error.default.hex}}" },
	
	# documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "{{colors.secondary.default.hex}}" },
	
	# Broken symbolic links
	{ name = "*", is = "orphan", fg = "{{colors.error.default.hex}}", crossed = true },
	{ name = "*/", is = "orphan", fg = "{{colors.error.default.hex}}", crossed = true },

	# Symbolic links
	{ name = "*", is = "link", fg = "{{colors.primary.default.hex}}" },
	{ name = "*/", is = "link", fg = "{{colors.primary.default.hex}}" },

	# Executable
	{ name = "*", is = "exec", fg = "{{colors.secondary.default.hex}}" },
	
	# Empty files
	{ mime = "inode/empty", fg = "{{colors.outline_variant.default.hex}}" },

	# Fallbback
	{ name = "*", fg = "{{colors.on_surface.default.hex}}" },
	{ name = "*/", fg = "{{colors.primary.default.hex}}" }
]
