#
#                                           - mayank19o7
#
#   8                              o   o
#   8                                  8
#   8 .oPYo. .oooo. o    o .oPYo. o8  o8P
#   8 .oooo8   .dP  8    8 8    8  8   8
#   8 8    8  oP'   8    8 8    8  8   8
#   8 `YooP8 `Yooo' `YooP8 `YooP8  8   8
# ::..:.....::.....::....8 :....8 :..::..::::::::::::::
# ::::::::::::::::::::ooP'.::ooP'.:::::::::::::::::::::
# ::::::::::::::::::::...::::...:::::::::::::::::::::::
# -----------------------------------------------------

git:
  pagers:
    - pager: delta --dark --paging=never
    - colorArg: always
gui:
  nerdFontsVersion: "3"
  authorColors:
    '*': '#0274a9'
  theme:
    activeBorderColor:
      - '#8ccdff'
      - bold
    inactiveBorderColor:
      - '#6d757d'
    searchingActiveBorderColor:
      - '#ebb2ff'
    optionsTextColor:
      - '#adcae3'
    selectedLineBgColor:
      - '#191d21'
    cherryPickedCommitFgColor:
      - '#8ccdff'
    cherryPickedCommitBgColor:
      - 'bg'
    unstagedChangesColor:
      - '#ffb4ab'
    defaultFgColor:
      - '#bfc7d0'
