#
#							- mayank19o7
# o   o                o
# `b d'
#  `b'  .oPYo. .oooo. o8
#   8   .oooo8   .dP   8
#   8   8    8  oP'    8
#   8   `YooP8 `Yooo'  8
# ::..:::.....::.....::..:::::::::::::::
# ::::::::::::::::::::::::::::::::::::::
# --------------------------------------


# --------------------------------------
# Manager
# --------------------------------------
[mgr]
ratio = [2,2,5]
show_hidden = true


# --------------------------------------
# Preview
# --------------------------------------
[preview]
tab_size = 4
